name: Pylint

on:
  push:
    paths:
      - '**/*.py'  # Trigger the workflow only for Python file changes
  pull_request:
    paths:
      - '**/*.py'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12.0"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Get changed Python files
        id: changed_files
        run: |
          # Fetch the list of modified or added Python files and quote them
          git fetch origin ${{ github.event.before }} --depth=1
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} HEAD -- '*.py' | sed 's/.*/"&"/')
          echo "Changed files: $CHANGED_FILES"
          echo "files=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Run pylint on changed files
        if: env.files != ''
        run: |
          echo "Linting the following files: ${{ env.files }}"
          pylint ${{ env.files }}
